### ISSUE TITLE
Show docker logs in read-only buffer

### ISSUE THREAD

**Issue by vlcinsky** [kevinhui/vim-docker-tools#16]
Thanks for great tool. Nice sort of dashboard.

The log buffer currently allows editing.

Other tools, like [tpope/dadbod](https://github.com/tpope/vim-dadbod), often use read-only (buffer with `modifiable` set `off) for such purposes. I guess [it is set here](https://github.com/tpope/vim-dadbod/blob/master/autoload/db.vim#L163). (note: I am not an VimScript expert)

This would prevent accidental modification of the content.

**Comment by vlcinsky** [comment]
@kevinhui I understand the motivation.

Anyway, there shall be no problem with using read-only buffer - it is important to be able selecting bunch of lines and copy it elsewhere, where it can be edited as needed. I have seen it done this way in multiple plugins (tpope/dadbod, but even ordinary neovim terminal works this way)

In fact, with read-only there is less space for confusion and unintended modification of the log output.

**Comment by kevinhui** [comment]
I understand your concern. It will be included in the next release

**Comment by vlcinsky** [comment]
Perfect. Consider removing the `wontfix` tag then.
