### ISSUE TITLE
Allow reloading image status manually

### ISSUE THREAD

**Issue by vlcinsky** [kevinhui/vim-docker-tools#17]
It seems, like the list of docker images is automatically reloaded once upon a time.

Sometime I was not sure, if it already provides the latest uptodate information and was searching for a method to reload the content.

Typically such an action is mapped to `r` key, which is currently taken by "restart" action.

I will create separate issue to propose alternative mappings.

**Comment by kevinhui** [comment]
FYI `CursorHold` is set for reloading the docker image. However, it does not work so good according to my experience(it will wash out the callback message after some time, too) and I will open an issue to review the refresh setting.
@jakecode has already added a key mapping for refresh and it will be released very soon.
