### ISSUE TITLE
show containers with filter

### ISSUE THREAD

**Issue by kevinhui** [kevinhui/vim-docker-tools#5]
regarding #4 ,should also be able to filter containers

**Comment by jakecode** [comment]
Is this planned to be implemented following the docker filter conventions for [docker ps](https://docs.docker.com/engine/reference/commandline/ps/#filtering), or did you have a different syntax in mind for it?

**Comment by kevinhui** [comment]
Hi Jake,
It will be using the same filter conventions as you expected.
