### ISSUE TITLE
add 'sudo' compatibility

### ISSUE THREAD

**Issue by stackpivot** [kevinhui/vim-docker-tools#9]
It's considered bad practice to add your user to the docker group, as this basically is a priv-esc vulnerability to root.

I would suggest to add a mode where you are actually calling _sudo_ to interact with docker

**Comment by kevinhui** [comment]
Good call. I will take a look at it

**Comment by kevinhui** [comment]
I will add an option `g:dockertools_sudo_mode` which will make all the docker commands executed in sudo mode when enabled. 
As neovim [does not](https://github.com/neovim/neovim/wiki/FAQ#-and-system-do-weird-things-with-interactive-processes) support interactive commands, neovim user will need to make sure sudo does not prompt for password.
For example, edit the sudoers file and add the following line will do the job:
```
username ALL = (root) NOPASSWD: path/to/docker
```
